[package]
name = "matcha-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "matcha"
path = "src/main.rs"

[dependencies]
matcha-ui = { path = "../matcha-ui" }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
